
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYWJw8I_SsFhMd-TTw3QkxIMsmGA5fA8Y',
    appId: '1:849832194782:android:e3d0d43685c8a6b4a5884f',
    messagingSenderId: '849832194782',
    projectId: 'moviesapp1-b9de7',
    storageBucket: 'moviesapp1-b9de7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyBPZJ3kU99_pBdbWEJjy0vrd8B0orCaS6Y',
      appId: '1:849832194782:ios:469243aa87f8bf94a5884f',
      messagingSenderId: '849832194782',
      projectId: 'moviesapp1-b9de7',
      storageBucket: 'moviesapp1-b9de7.appspot.com',
      iosBundleId: 'com.example.moviesapp1',
      );
}